# Generated by Django 4.1.4 on 2022-12-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='navid.g.h.909xx@gmail.com', max_length=254)),
                ('adress', models.CharField(default='', max_length=256)),
                ('phonenumber', models.CharField(default='', max_length=13)),
                ('instagram', models.CharField(default='prodnavid', max_length=256)),
                ('linkedin', models.CharField(default='', max_length=256)),
                ('about', models.CharField(default='I am Navid And Create Beat', max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
