# Generated by Django 4.1.4 on 2022-12-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelNavid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stop_seling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram',
            field=models.CharField(blank=True, default='prodnavid', max_length=256),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phonenumber',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
    ]
