# Generated by Django 4.1.4 on 2022-12-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelNavid', '0002_sitesettings_stop_seling_alter_sitesettings_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cdn_active',
            field=models.BooleanField(default=False),
        ),
    ]
