# Generated by Django 4.1.4 on 2022-12-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelNavid', '0006_message_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='pooya.rezaee.official@gmail.com', max_length=254)),
                ('phonenumber', models.CharField(blank=True, default='+989396231180', max_length=13)),
                ('instagram', models.CharField(blank=True, default='', max_length=256)),
                ('github', models.CharField(blank=True, default='https://github.com/pooyarezaee', max_length=256)),
                ('linkedin', models.CharField(blank=True, default='https://linkedin.com/in/pooya-rezeemoghadam', max_length=256)),
                ('about', models.CharField(default='I am PooyaRezaee(Developer This WebApplication)', max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
