# Generated by Django 4.1.4 on 2022-12-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelNavid', '0007_infodeveloper'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='background',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
