# Generated by Django 4.1.4 on 2022-12-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelNavid', '0010_alter_sitesettings_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='background/'),
        ),
    ]
