# Generated by Django 4.1.4 on 2022-12-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelNavid', '0011_alter_sitesettings_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infodeveloper',
            name='about',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about',
        ),
        migrations.AddField(
            model_name='infodeveloper',
            name='about_en',
            field=models.CharField(default='I am PooyaRezaee(Developer This WebApplication)', max_length=1024, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='infodeveloper',
            name='about_fa',
            field=models.CharField(default='I am PooyaRezaee(Developer This WebApplication)', max_length=1024, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_en',
            field=models.CharField(default='I am Navid And Create Beat', max_length=1024, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_fa',
            field=models.CharField(default='I am Navid And Create Beat', max_length=1024, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=256, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=30, verbose_name='Subject'),
        ),
    ]
