# Generated by Django 4.1.4 on 2022-12-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelNavid', '0012_remove_infodeveloper_about_remove_sitesettings_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infodeveloper',
            name='about_en',
            field=models.CharField(default='I am PooyaRezaee(Developer This WebApplication', max_length=1024, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='infodeveloper',
            name='about_fa',
            field=models.CharField(default='I am PooyaRezaee(Developer This WebApplication', max_length=1024, verbose_name='about'),
        ),
    ]
