# Generated by Django 4.1.4 on 2022-12-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockListIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='view',
            name='ip_addr',
            field=models.CharField(max_length=20),
        ),
    ]
