# Generated by Django 4.1.4 on 2022-12-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ear', '0002_blocklistip_alter_view_ip_addr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View',
            new_name='IpLog',
        ),
    ]
