# Generated by Django 4.1.4 on 2022-12-09 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ear', '0003_rename_view_iplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='iplog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
