# Generated by Django 4.1.4 on 2022-12-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ear', '0004_iplog_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iplog',
            name='created',
        ),
    ]
