# Generated by Django 4.1.4 on 2022-12-11 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ear', '0005_remove_iplog_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='iplog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
