# Generated by Django 4.1.4 on 2022-12-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
