# Generated by Django 4.1.4 on 2022-12-14 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beat', '0005_alter_beat_audio_beat_alter_beat_image_beat_and_more'),
        ('order', '0004_alter_payment_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='beat',
            field=models.ForeignKey(default=django.db.models.deletion.RESTRICT, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order', to='beat.beat'),
        ),
    ]
