# Generated by Django 4.1.4 on 2022-12-09 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, unique=True)),
                ('title', models.CharField(max_length=32)),
                ('audio_beat', models.FileField(upload_to='beat/audio/%Y/%m/%d')),
                ('time_audio', models.IntegerField(blank=True, null=True)),
                ('image_beat', models.ImageField(upload_to='beat/image/%Y/%m/%d')),
                ('type', models.CharField(choices=[('D', 'demo'), ('F', 'full')], max_length=1)),
                ('price', models.PositiveIntegerField()),
                ('is_show', models.BooleanField(default=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('slug', models.SlugField()),
                ('on_home', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ipaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='BeatHits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beat.beat')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beat.ipaddress')),
            ],
        ),
        migrations.AddField(
            model_name='beat',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='beat.category'),
        ),
        migrations.AddField(
            model_name='beat',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='beat.BeatHits', to='beat.ipaddress'),
        ),
    ]
