# Generated by Django 4.1.4 on 2022-12-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='title',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
