# Generated by Django 4.1.4 on 2022-12-11 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beat', '0002_alter_beat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beats', to='beat.category'),
        ),
    ]
