# Generated by Django 4.1.4 on 2022-12-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat', '0003_alter_beat_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='main_beat',
            field=models.FileField(blank=True, null=True, upload_to='beat/origin/%Y/%m/%d'),
        ),
    ]
