# Generated by Django 4.1.4 on 2022-12-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat', '0004_beat_main_beat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='audio_beat',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='beat',
            name='image_beat',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='beat',
            name='main_beat',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
