# Generated by Django 4.1.4 on 2022-12-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat', '0005_alter_beat_audio_beat_alter_beat_image_beat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='audio_beat',
            field=models.FileField(upload_to='public/'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='image_beat',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='main_beat',
            field=models.FileField(blank=True, null=True, upload_to='prive/'),
        ),
    ]
