# Generated by Django 4.1.4 on 2022-12-16 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beat', '0006_alter_beat_audio_beat_alter_beat_image_beat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beathits',
            name='beat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beat.beat'),
        ),
    ]
