# Generated by Django 4.1.4 on 2022-12-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat', '0007_alter_beathits_beat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default=0, max_length=16, verbose_name='Category Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(default=1, max_length=16, verbose_name='Category Name'),
            preserve_default=False,
        ),
    ]
