# Generated by Django 4.1.4 on 2022-12-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beat', '0008_remove_category_name_category_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beathits',
            name='beat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beat.beat'),
        ),
    ]
